### PR TITLE
Bump quickcheck to 0.9

### PR DESCRIPTION
**Pull request by eclipseo**

### CODE REVIEW

**Comment by BurntSushi** [comment]
Nope. It bumps the MSRV and I'm not ready to do that. Sorry.

**Comment by ethanpailes** [comment]
Wouldn't it be ok because quickcheck is just a dev dependency? Is it just that having a different MSRV for dev vs non-dev makes testing and locking an MSRV in CI much harder?

**Comment by BurntSushi** [comment]
Normally it would be fine. But rand is using a new feature in Cargo.toml that breaks non-dev builds on older versions of Rust. Just try a normal build on Rust 1.28 and you should see the error.

**Comment by ethanpailes** [comment]
Gotcha

**Pull request closed without merging**
