### PR TITLE
Update Computer Language Benchmarks Game URL

### PR DESCRIPTION
**Pull request by atouchet**
This URL appears to have moved since these were last edited.

### CODE REVIEW

**Comment by evertondanilo** [comment]
@BurntSushi Did you participate in Rust coding on CLBG? I'd like to port Rust to Wasm and run some performance tests.

**Comment by BurntSushi** [comment]
@evertondanilo I don't understand what you're asking and what it has to do with this PR. Please say more words.

**Comment by evertondanilo** [comment]
Hi @BurntSushi thanks for your quick reply. I'm working on a research project for my masters. The idea is to compare Wasm with JS in the browser. And find out how fast it would be? Do you think CLBG algs can be compiled to Wasm?

**Comment by BurntSushi** [comment]
I don't know why you're asking me that question on the issue tracker for a regex library.

> Do you think CLBG algs can be compiled to Wasm?

Why not try it?

I think this line of questioning is way off topic for this tracker. Please take it somewhere else.

**Pull request merged**
