### PR TITLE
[docs] Fix words duplication in docs `extract`

### PR DESCRIPTION
**Pull request by denzenin**
Fix words duplication in docs `extract` in three files.

### CODE REVIEW

**Review by BurntSushi — CHANGES_REQUESTED** [review]
Please reflow the text.

**Review by BurntSushi — APPROVED** [review]

**Comment by denzenin** [comment]
@BurntSushi Andrew, hi. Thanks for checking my PR so quickly. I am just starting with rust, can you please advise how do  you automatically reflow text in the comments? It looks like `rustfmt` does not touch comments by default

**Comment by BurntSushi** [comment]
@denzenin Good question. I don't have a way of doing it automatically unfortunately. Instead, I do it manually via a combination of the [`par`](http://www.nicemice.net/par/) CLI utility and [neovim keybindings](https://github.com/BurntSushi/dotfiles/blob/f52cb7b0213a98690bddc73b3c60654a99942865/.config/nvim/include/keybinds.vim#L11-L20).

**Comment by denzenin** [comment]
@BurntSushi thanks for the tips :)

**Pull request merged**
