### PR TITLE
better support for empty patterns

### PR DESCRIPTION
**Pull request by sliquister**
I propose fixing the known issue in compile.rs where empty patterns + alternations can cause compilation errors or be compiled into a wrong automaton.

I understand that the plan is to replace compile.rs with a better version, but this doesn't seem to be about to happen, and I think the fix is not an undue amount of work. If possible, I would prefer fixing `regex` than work around these issues (it's easy to avoid them in hand written regexes but when generating regexes, it's more annoying).

About the change itself: all I do is compile `Empty` into `Ok(None)` instead of `Ok(Patch{ entry: the-next-instruction, ..})` (as that is not correct in general) and follow the type system. I tried fixing this in other ways with less diff, but I think this version is simpler: the diff is bigger (mostly due to changes types and indentation, which are easy to review) but the performance is clearly ok and the type system forces me to consider where changes need to happen. The kind of diff `self.c(expr)? ` -> `self.c(expr)?.unwrap_or(self.next_inst());` is saying "at this call site, the old behavior worked".

The same automation should be generated in the case that were previously correctly and successfully compiled, except a few corner cases that involve empty subexpressions, where we may generate fewer instructions (like `(?:)?`).

### CODE REVIEW

**Comment by sliquister** [comment]
For the test failure:

```
thread 'hir::translate::tests::analysis_is_alternation_literal' panicked at 'assertion failed: t(r"").is_alternation_literal()', regex-syntax/src/hir/translate.rs:3127:9
```

should the documentation of hir and implementation of exec.rs be changed to accept Empty nodes in is_alternation_literal?

**Comment by BurntSushi** [comment]
@sliquister Good question. The docs suggest that `""` shouldn't be an alternation literal, so I'd go with what you have and adjust the tests as appropriate. Updating the docs to add `""` to the list of negative examples would also be good.

**Comment by sliquister** [comment]
Thanks, the tests all pass now (and I've learned of the existence of `cargo test --all`).

**Comment by sliquister** [comment]
Have you had a chance to consider this? (I'm trying to decide if I need to workaround the underlying issue)

**Comment by BurntSushi** [comment]
This PR is in `regex 1.3.8` on crates.io.

As a bonus, this also fixed #659!

**Comment by sliquister** [comment]
Marvelous, thank you! (especially with this change being released immediately)

**Pull request closed without merging**
