### PR TITLE
Implement Ord for Class

### PR DESCRIPTION
**Pull request by pczarn**
Added Ord and PartialOrd for Class, IntervalSet,
ClassUnicode and ClassBytes

### CODE REVIEW

**Comment by pczarn** [comment]
This probably needs a minor version bump.

**Comment by RReverser** [comment]
Why though? Classes and sets don't really have a well-defined ordering semantics.

**Comment by pczarn** [comment]
@RReverser should I implement Hash instead? Or should I use vecs of classes instead of maps? I wanted to use classes in map keys.

**Comment by RReverser** [comment]
To be clear - I'm not a maintainer here, and my position doesn't mean much, but personally I find these traits misleading when they're implemented just for inclusion in other data structures, without actual well-defined ordering on the type.

`Hash` is IMO better, because it doesn't require any defined semantics.

**Comment by BurntSushi** [comment]
@pczarn Could you say more about the high level problem you're trying to solve here?

@RReverser Note that these aren't just sets. These are ordered sets, and that is guaranteed as part of their public API. So in that sense, I think `Ord` impls do have an "obvious" semantics.

**Comment by RReverser** [comment]
> These are ordered sets, and that is guaranteed as part of their public API.

Their elements are ordered, sure, but ordering of sets with each other seems less obvious.

**Comment by BurntSushi** [comment]
Yeah, I wrote out a few examples and it does seem a bit weird. Using the definition in this PR for example:

```
[[1, 5]] > [[1, 4]]
[[1, 5]] > [[1, 4], [5, 5]]
```

The latter one should be equivalent in my view. Although, `Class` does have the property that any two adjacent ranges are _not_ continuous. But maybe there are more weird examples like this.

@pczarn I think implementing `Hash` for this would be uncontroversial. I'd be potentially open to `Ord`, but I think I'd need to see a more rigorous argument for it.

**Pull request closed without merging**
