### PR TITLE
bump quickcheck to 0.5

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Seems it is not that trivial...

**Comment by BurntSushi** [comment]
@ignatenkobrain You're really on top of things! But yeah, there might be some breaking changes that need to be fixed.

**Comment by ignatenkobrain** [comment]
```rust
error[E0308]: mismatched types

   --> regex-syntax/src/properties.rs:194:51

    |

194 |                                       e: Box::new(e),

    |                                                   ^ expected enum `Expr`, found struct `std::boxed::Box`

    |

    = note: expected type `Expr`

               found type `std::boxed::Box<Expr>`

error[E0271]: type mismatch resolving `<[closure@regex-syntax/src/properties.rs:193:40: 197:36 i:_, name:_] as std::ops::FnOnce<(std::boxed::Box<Expr>,)>>::Output == std::boxed::Box<Expr>`

   --> regex-syntax/src/properties.rs:192:28

    |

192 |                           .chain(e.clone().shrink()

    |                            ^^^^^ expected enum `Expr`, found struct `std::boxed::Box`

    |

    = note: expected type `Expr`

               found type `std::boxed::Box<Expr>`

    = note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Map<std::boxed::Box<std::iter::Iterator<Item=std::boxed::Box<Expr>>>, [closure@regex-syntax/src/properties.rs:193:40: 197:36 i:_, name:_]>`

error[E0271]: type mismatch resolving `<std::iter::Chain<std::boxed::Box<std::iter::Iterator<Item=std::boxed::Box<Expr>>>, std::iter::Map<std::boxed::Box<std::iter::Iterator<Item=std::boxed::Box<Expr>>>, [closure@regex-syntax/src/properties.rs:193:40: 197:36 i:_, name:_]>> as std::iter::Iterator>::Item == Expr`

   --> regex-syntax/src/properties.rs:191:17

    |

191 | /                 Box::new(e.clone().shrink()

192 | |                           .chain(e.clone().shrink()

193 | |                                   .map(move |e| Group {

194 | |                                       e: Box::new(e),

195 | |                                       i: i.clone(),

196 | |                                       name: name.clone(),

197 | |                                   })))

    | |______________________________________^ expected struct `std::boxed::Box`, found enum `Expr`

    |

    = note: expected type `std::boxed::Box<Expr>`

               found type `Expr`

    = note: required for the cast to the object type `std::iter::Iterator<Item=Expr>`

error[E0271]: type mismatch resolving `<[closure@regex-syntax/src/properties.rs:193:40: 197:36 i:_, name:_] as std::ops::FnOnce<(std::boxed::Box<Expr>,)>>::Output == std::boxed::Box<Expr>`

   --> regex-syntax/src/properties.rs:191:17

    |

191 | /                 Box::new(e.clone().shrink()

192 | |                           .chain(e.clone().shrink()

193 | |                                   .map(move |e| Group {

194 | |                                       e: Box::new(e),

195 | |                                       i: i.clone(),

196 | |                                       name: name.clone(),

197 | |                                   })))

    | |______________________________________^ expected enum `Expr`, found struct `std::boxed::Box`

    |

    = note: expected type `Expr`

               found type `std::boxed::Box<Expr>`

    = note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Map<std::boxed::Box<std::iter::Iterator<Item=std::boxed::Box<Expr>>>, [closure@regex-syntax/src/properties.rs:193:40: 197:36 i:_, name:_]>`

    = note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Chain<std::boxed::Box<std::iter::Iterator<Item=std::boxed::Box<Expr>>>, std::iter::Map<std::boxed::Box<std::iter::Iterator<Item=std::boxed::Box<Expr>>>, [closure@regex-syntax/src/properties.rs:193:40: 197:36 i:_, name:_]>>`

    = note: required for the cast to the object type `std::iter::Iterator<Item=Expr>`

error: aborting due to 4 previous errors
```

Not entirely sure how to fix it... yet.

**Comment by BurntSushi** [comment]
That looks suspicious. I'll try to investigate later today.

**Comment by ignatenkobrain** [comment]
@BurntSushi I give up, have no idea why it doesn't work.

**Comment by BurntSushi** [comment]
I'll check it out when I get a chance. Thanks for trying! It is quite interesting that Windows CI passed...

**Comment by ignatenkobrain** [comment]
Just some hint: it started to happen after https://github.com/BurntSushi/quickcheck/commit/6c9629051347a2be22c6f6111fe9fba3f0fdeac3

**Comment by BurntSushi** [comment]
Oh hmm yeah, that's from this PR, which we noted as a breaking change: https://github.com/BurntSushi/quickcheck/pull/154

**Comment by ignatenkobrain** [comment]
@BurntSushi @cuviper wrote patch which I committed. Should work just fine.

Also he pointed out that clone() is not necessary and could be replaced by: `*e.clone()` -> `**e`. Not sure if I should go with this option because I see clone() everywhere in the code.

**Comment by BurntSushi** [comment]
@ignatenkobrain Interesting, thanks for the fix! The extra `clone` is fine even if it isn't necessary, this is just test code after all.

@bors r+

**Comment by BurntSushi** [comment]
C'mon bors! @bors r+

**Comment by BurntSushi** [comment]
@ignatenkobrain Oh interesting. Did bors pick up on the "WIP" in the issue title? Cute.

**Pull request merged**
