### PR TITLE
Update pattern.rs to remove redundancy

### PR DESCRIPTION
**Pull request by saki-osive**
Remove redundancy in RegexSearcher impl function into_searcher.

### CODE REVIEW

**Comment by BurntSushi** [comment]
There are a lot of these types of simplifications that can be made in this crate, since a lot of the code was written before the shorthand syntax existed. I'd prefer to fix them in one fell swoop rather than chopping away at them one-by-one.

**Comment by saki-osive** [comment]
@BurntSushi Could I fix all and re-open this?

**Comment by BurntSushi** [comment]
Sure.

**Comment by BurntSushi** [comment]
Closing due to inactivity.

**Pull request closed without merging**
