### PR TITLE
Move oss fuzz build scripts + update with debug-assertions

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
I'll follow up shortly with a PR in oss-fuzz. This one will need to be merged before the oss-fuzz one can be.

**Comment by BurntSushi** [comment]
Can you remove the license notice please? I don't think it's needed here. And the Rust project generally doesn't put license notices in the headers of files. It's basically just noise.

**Comment by silvergasp** [comment]
If you don't mind commenting/reviewing/approving here https://github.com/google/oss-fuzz/pull/10369 that'll speed things along once I mark it ready for review.

**Review by BurntSushi — APPROVED** [review]
LGTM. So if I want to run more fuzzers, I just copy them into the `$OUT` directory? Neat!

**Pull request merged**
