### PR TITLE
fuzz: do not use inherits in Cargo.toml

### PR DESCRIPTION
**Pull request by catenacyber**
to fix oss-fuzz build
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36474

cc @BurntSushi @DavidKorczynski

### CODE REVIEW

**Review by BurntSushi — APPROVED** [review]
Nice! If you don't mind me asking, how did you debug this? I remember looking at the fuzz failure, and it wanted me to do a song-and-a-dance to debug it and I didn't have time to dig into it. And also, what was wrong with using `inherits` here?

**Comment by catenacyber** [comment]
I looked at the ailing build log
https://oss-fuzz-build-logs.storage.googleapis.com/log-c9b61873-8950-4a50-a729-820d5617ff7a.txt

> Step #3 - "compile-libfuzzer-address-x86_64": error: `inherits` must not be specified in root profile `dev`

I tried looking for `inherits` in cargo's doc but did not find any mention

**Comment by BurntSushi** [comment]
Perfect. That sounds like a much better commit message. :-) I've copied it into the message.

**Comment by catenacyber** [comment]
Thanks for rewording the commit

**Pull request merged**
