### PR TITLE
Issue 348

### PR DESCRIPTION
**Pull request by ethanpailes**
I took a crack at implimenting #348, but ended up running into some squirrly results with the benchmark that I wrote. During some runs the optimization behaved as expected, but for most there was no real corrilation between input size and performance. I suspect I'm missing some benchmarking trick, so an insight would be appreciated. The steps I used to test the benchmark are outlined in a comment above the new benchmarks I added (in `bench/src/misc.rs`).

For now I've just done the anchor optimization.

As I was learning about the code base I also noticed a few documentation references that had drifted out of date, so I fixed those.

### CODE REVIEW

**Comment by BurntSushi** [comment]
@ethanpailes Thanks so much for putting in the work for this optimization! It might take me a bit to review this, but I just wanted to chime in. :-)

**Comment by ethanpailes** [comment]
Unfortunatly, I did end up in a place where you have more review work than I would have hoped because of those weird benchmark results, so it makes sense that it might take a little while to review.

**Comment by BurntSushi** [comment]
I've rolled this PR into https://github.com/rust-lang/regex/pull/436. Thanks!

**Comment by BurntSushi** [comment]
@ethanpailes There should definitely be a way to observe a performance difference on unanchored regexes, but the anchored optimization is definitely a step in the right direction. I don't quite have time to do the benchmark analysis for unanchored regexes though. From briefly looking at your regexes, my gut says that you need to make the match bigger.

**Pull request closed without merging**
