### PR TITLE
Fixed compilation errors

### PR DESCRIPTION
**Pull request by gchp**

### CODE REVIEW

**Comment by gchp** [comment]
I currently can't compile regex. See this comment for info: https://github.com/rust-lang/regex/issues/50#issuecomment-77153302

**Comment by BurntSushi** [comment]
I get the same over here. I ran it under `valgrind`:

```
 valgrind rustc src/lib.rs --crate-name regex --crate-type lib -g -C metadata=64952606b89c7990 -C extra-filename=-64952606b89c7990 --out-dir /home/andrew/data/projects/rust/regex/target --emit=dep-info,link -L dependency=/home/andrew/data/projects/rust/regex/target -L dependency=/home/andrew/data/projects/rust/regex/target/deps
```

and got this: https://gist.github.com/087f0afda9e422cd44b1 --- bug in rustc? This is all the investigation I can do at the moment though. :-(

**Comment by BurntSushi** [comment]
@alexcrichton ping. :-)

**Comment by alexcrichton** [comment]
Hm, fascinating!  Looks like rust-lang/rust#23032 has the segfault issue covered and the changes in #52 don't cause a segfault, so I'll merge that for now.

**Comment by alexcrichton** [comment]
Thanks regardless!

**Pull request merged**
