### PR TITLE
Add a script to manage marker traits

### PR DESCRIPTION
**Pull request by alexfertel**
Closes https://github.com/rust-lang/regex/issues/756.

This PR introduces a Python script named `public-types-tests.py` that manages marker traits for the public API types. Following the discussion in https://github.com/rust-lang/regex/issues/756, this script is responsible for two tasks:

* Generate a test that asserts marker traits being implemented on the public API types (This test might need to be tweaked so it passes). This is done by generating the docs for this crate, parsing them, and
writing the assertions to the file `tests/marker_traits.rs`. This shouldn't have to be done very often, probably just once. We pass the `-g` flag as an argument to the script to generate the tests.
* Check the existence of marker-trait tests for each public API type, failing if it doesn't find *at least* one of the possible four.

This accomplishes three objectives:

* Automate generating the assertion for each type.
* Failing CI when a new type is added because no test related to it exists.
* Avoid regressions in current types having marker traits auto-implemented.

Two things remain for this PR to be ready:

- [x] Add comments to the script.
- [x] Setup CI.

### CODE REVIEW

**Comment by alexfertel** [comment]
@BurntSushi Let me know if this is somewhat near what you had in mind.

**Comment by alexfertel** [comment]
@BurntSushi Sorry to bother, is something blocking this PR, or is it way too different from what you expected? 🥺

**Comment by BurntSushi** [comment]
Haven't had a chance to look yet, sorry. I have a baby at home and the past few weeks have been hectic.

**Comment by alexfertel** [comment]
@BurntSushi  Oh, no worries at all. Congrats!!! Sorry for bothering 😅

**Review by BurntSushi — CHANGES_REQUESTED** [review]
OK, so I've finally had a chance to look at this. I also re-read #756, and I feel like there was a miscommunication perhaps. In particular, I specifically do not want extra automation for generating the tests. It's effectively extra code for _almost_ no value. The public API just does not change much. So adding a new test by hand is done once in a blue moon and it doesn't cost much to do.

The _only_ thing I really want here is something to tell me whether a new test needs to be added or not, and then run that in CI. I see that here, which is great. But I really think it should just be a shell script. I have _almost_ gotten rid of Python from this repo, so I'd rather not bring more of it in.

I realize this is a really tardy review, so feel free to just drop this. The baby has kept me very busy. But if you're looking to keep going here, I'd say:

1. Drop all the codegen.
2. Convert the existence check to a simple shell script.

**Comment by BurntSushi** [comment]
I'm going to close this out due to inactivity, but I would still like something _simple_ that checks that we're covering the API with tests for marker traits.

**Pull request closed without merging**
