### PR TITLE
Update to rust master: fixed array length fixes + lib stabilizations

### PR DESCRIPTION
**Pull request by vhbit**

### CODE REVIEW

**Comment by pyfisch** [comment]
Build passes.
But tests still fail to build for me.

**Comment by vhbit** [comment]
It looks pretty much like an error from fixed length array change, but I can't test yet as I have a local dylib mess and `regex_macros` fails to build at all.

**Comment by vhbit** [comment]
@pyfisch I've pushed an update, can you test it as I'm not sure how long it will take to solve dylib issue?

**Comment by pyfisch** [comment]
All builds pass. (Like on travis) for ac2a0dc

**Comment by pyfisch** [comment]
All is ok. 
The deprecated things can probably changed in a separate pr.
* deprecated syntax; use the `self` keyword now
* `deriving` is deprecated; use `derive`

**Comment by vhbit** [comment]
Pushed update for deprecation just a couple seconds ago :smile:

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
