### PR TITLE
remove regex plugin + rollup + chores

### PR DESCRIPTION
**Pull request by BurntSushi**
This PR:

* Removes the regex compiler plugin. It's been broken for quite some time and nobody has seemed to notice. It's time for it to go. See commit cc7b00c for details.
* Setup a Cargo workspace for this repo.
* Update deps in various places. This includes updating simd to `0.2.1`, which fixes a build failure on Rust nightly.
* Name the frequency analysis based memchr search "freqy packed."
* Rolls up the other open PRs #401, #410 and #433.

### CODE REVIEW

**Comment by BurntSushi** [comment]
cc @ethanpailes Note that in commit 392b3d6 I tweaked the TBM heuristic a little bit.

**Comment by ethanpailes** [comment]
@BurntSushi, I know I'm a bit late to the party, but that new heuristic looks great. Thanks for doing the `LEN_CUTOFF_PROPORTION` stuff! I had been planning on trying to find a good value for something like that, but now it is already done!

**Pull request merged**
